export enum TransferStatus {
  PENDING = "pending",
  INITIATED = "initiated",
  PROCESSING = "processing",
  SUCCESS = "success",
  CANCELED = "canceled",
  FAILED = "failed",
  REFUNDED = "refunded",
}

export enum TransferType {
  SEND = "send",
  RECEIVE = "receive",
  WITHDRAW = "withdraw",
  DEPOSIT = "deposit",
  BRIDGE = "bridge",
  BANK_DEPOSIT = "bank_deposit",
}

export enum PurposeCode {
  SELF = "self",
  SALARY = "salary",
  GIFT = "gift",
  INCOME = "income",
  SAVING = "saving",
  EDUCATION_SUPPORT = "education_support",
  FAMILY = "family",
  HOME_IMPROVEMENT = "home_improvement",
  REIMBURSEMENT = "reimbursement",
}

export enum Currency {
  USD = "USD",
  INR = "INR",
  AED = "AED",
  IDR = "IDR",
  PKR = "PKR",
  SGD = "SGD",
  EUR = "EUR",
  MYR = "MYR",
  CAD = "CAD",
  KYD = "KYD",
  LBP = "LBP",
  TRY = "TRY",
  XCD = "XCD",
  VND = "VND",
  THB = "THB",
  HKD = "HKD",
  BDT = "BDT",
  PHP = "PHP",
  KHR = "KHR",
  AUD = "AUD",
  GBP = "GBP",
  NPR = "NPR",
  LKR = "LKR",
  XOF = "XOF",
  XAF = "XAF",
  GHS = "GHS",
  KES = "KES",
  MZN = "MZN",
  TZS = "TZS",
  UGX = "UGX",
  NZD = "NZD",
  KRW = "KRW",
  MMK = "MMK",
  JPY = "JPY",
  BRL = "BRL",
  CNY = "CNY",
  USDC = "USDC",
  USDT = "USDT",
  DAI = "DAI",
  ETH = "ETH",
  USDCE = "USDCE",
  STR = "STR",
}

export enum SourceOfFunds {
  SALARY = "salary",
  SAVINGS = "savings",
  LOTTERY = "lottery",
  INVESTMENT = "investment",
  LOAN = "loan",
  BUSINESS_INCOME = "business_income",
  OTHERS = "others",
}

export enum TransferStep {
  NONE = "none",
  SEND_EMAIL_RECIPIENT = "send_email_recipient",
  SEND_WALLET_RECIPIENT = "send_wallet_recipient",
  SEND_AMOUNT = "send_amount",
  SEND_PURPOSE = "send_purpose",
  SEND_CONFIRMATION = "send_confirmation",
  WITHDRAW_WALLET_ADDRESS = "withdraw_wallet_address",
  WITHDRAW_AMOUNT = "withdraw_amount",
  WITHDRAW_PURPOSE = "withdraw_purpose",
  WITHDRAW_CONFIRMATION = "withdraw_confirmation",
  BANK_WITHDRAW_AMOUNT = "bank_withdraw_amount",
  BANK_WITHDRAW_COUNTRY = "bank_withdraw_country",
  BANK_WITHDRAW_PURPOSE = "bank_withdraw_purpose",
  BANK_WITHDRAW_CONFIRMATION = "bank_withdraw_confirmation",
  BANK_WITHDRAW_QUOTE = "bank_withdraw_quote",
}
